[package]
name = "adze-store"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
ordered-float = "4.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "tree_embedding"
harness = false
